

# This file was *autogenerated* from the file subspace-count.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4)
def avoids_arrangement(subspace,arrangement):
    for w in arrangement:
        if subspace.intersection(w).dimension() > _sage_const_0 :
            return False
    
    return True

def count_subspaces(d,n,q,facets):
    V = VectorSpace(GF(q),n)
    subspaces = V.subspaces(dim=d)

    W = []
    for sigma_j in facets:
        W.append(V.subspace([V.basis()[i] for i in sigma_j]))
    
    count = _sage_const_0 
    for H in subspaces:
        if avoids_arrangement(H,W):
            count += _sage_const_1 

    return count

Q = [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ]

for q in Q:
    print(count_subspaces(_sage_const_2 ,_sage_const_5 ,q,[[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_3 ,_sage_const_4 ]]))

